### PR TITLE
Clock 2 - Only needs to redraw once per second.

### PR DESCRIPTION
**Pull request by TheEyeOfBrows**
Only redraws if one of the displayed numbers have changed (or the canvas is resized).
Noticed that we are already bumping into some cpu issues.  We may want to make an issue topic on the subject.

### CODE REVIEW

**Comment by meiamsome** [comment]
Hmm, this is definitely an issue but I'm not sure this is the right way to solve it. Looking at the GIFs on Golan Levin's page it shows that the clocks don't actually animate unless they're moused over. This is something that I intend to implement, but it's useful to have all clocks animating at the moment for development. This can be done in the external code so that the clock doesn't need to know if it's animating or not. I'll think about this some more but for the moment I won't merge this

**Comment by TheEyeOfBrows** [comment]
This PR was only supposed to lower the number of redundant redraws, since the clock only changes once per second (unlike most of the clocks). 
I'd argue for the change, even if it were the only clock being run.

**Comment by meiamsome** [comment]
Sure, but clocks 2, 4, 5, 7, 9, 10 & 12 all only update once per second - so probably the easiest optimization is to set their frame rate to something like 5, and leave the others as something else..

**Comment by meiamsome** [comment]
@TheEyeOfBrows Hello, can you see if the latest version helps performance for you?

**Comment by TheEyeOfBrows** [comment]
It's a lot better now, for sure.

I can see a bit of lag/freezing when the seconds flip over (easiest to see in clocks 8 and 1). Not sure if there's anything we can do about that.

I'll close this pull request for now, as the immediate issue is resolved.

**Pull request closed without merging**
