### PR TITLE
Update clock-07.js

### PR DESCRIPTION
**Pull request by alebas96**

### CODE REVIEW

**Comment by meiamsome** [comment]
This seems to just replace the old clock with a new one dependant on a missing font file... What is this intending to change?

**Comment by alebas96** [comment]
I committed because the previous one had not the flashing dots between
hours and minuta every seconds. I ll upload the font

AB

Il 30 set 2017 00:38, "Oliver Wright" <notifications@github.com> ha scritto:

**Comment by alebas96** [comment]
https://www.dafont.com/it/minecraftia.font this is the font I used

**Comment by meiamsome** [comment]
I'm going to close this, preferring #28 - mostly because including the font seems unnecessary and may have attached licensing issues, sorry.

**Pull request closed without merging**
