### PR TITLE
Implemented clock 11

### PR DESCRIPTION
**Pull request by waielal**

### CODE REVIEW

**Comment by meiamsome** [comment]
Looks great. Merging quickly so it's in for the stream!

**Comment by meiamsome** [comment]
Looking at this code properly - I really appreciate how this is coded... it's really quite clever

**Comment by TheEyeOfBrows** [comment]
This is a great implementation!

**Comment by shiffman** [comment]
Wow, this is amazing!

**Comment by waielal** [comment]
Thanks, this means a lot to me. :blush:

**Pull request merged**
