### PR TITLE
Made Clock 9

### PR DESCRIPTION
**Pull request by haideralipunjabi**
I attempted to make Clock 9. :smile: 

Thanks to @FantasyTeddy for the fonts, and drawText function. Although I added a size parameter to it

### CODE REVIEW

**Comment by meiamsome** [comment]
This is for the clock made of mini-clocks, right? I think I managed to get the numbers the wrong way round for the comments in clocks 9 and 10. Apart from that, it's a good start to the clock - I'll fic that numbering issues.

I might prefer to make a list of collaborators for each of the clocks rather than having author names at the top of the files - would you be okay if I were to remove your comment at the top after getting that sorted out?

**Comment by haideralipunjabi** [comment]
Oh. I never knew those dots were supposed to be smaller clocks. Couldn't see it in [the gif](http://cmuems.com/2016/60212/wp-content/uploads/2016/09/maeda-all.gif). I will begin making it like that.
Yeah you can remove the comment at the top.

**Comment by meiamsome** [comment]
Yeah - somewhat confusingly as well the posts' gifs are numbered badly (Hence my numbers) You can see a fuller size of the clocks to look at here: http://cmuems.com/2016/60212/wp-content/uploads/2016/09/maeda-10.gif

**Comment by meiamsome** [comment]
@haideralipunjabi I merged this with some formatting tweaks, let me know if you're working on the clocks!

**Comment by haideralipunjabi** [comment]
@meiamsome Yeah I am working on them, might take a day or two

**Pull request merged**
